version: "3.8"
services:
  myapp-dev:
    image: nginx:latest
    container_name: myapp-dev
    ports:
      - "8081:80"
    volumes:
      - ./deve:/usr/share/nginx/html
    networks:
      - myapp-net

  myapp-prod:
    image: nginx:latest
    container_name: myapp-prod
    ports:
      - "8082:80"
    volumes:
      - ./prod:/usr/share/nginx/html
    networks:
      - myapp-net

networks:
  myapp-net:
    driver: bridge
